library(shiny)
library(glue)
ui<-fluidPage(
  sidebarLayout(
    sidebarPanel(
      h3("sinus generator"),
     
      numericInput(inputId = "x_max", label = "Maximum x axis value", value=10, min=1),
      conditionalPanel(
        "input.x_max>0",
        textInput(inputId="title","Title"),
        textInput(inputId="generated_by", "Generated by:")
      ),
      width = 2
    ),
    mainPanel(
      plotOutput("sine"),
      tableOutput("plot_table"),
      textOutput("gen_by"),
      width = 10
    )
  )
)


server <-function(input,output,session){
  
  plot_data  <-reactiveVal(NULL)
  
  observeEvent(input$x_max, {
    if(identical(input$x_max>0,TRUE)){
      x <- seq(0,input$x_max,by=0.1)
      df<- data.frame(x=x,y=sin(x))
      plot_data(df)
    }else{
      plot_data(NULL)
    }
  }
  )
  
  
  
  output$sine <- renderPlot({
    validate(need(!is.null(plot_data()),message = "novaliddata"))
    plot(plot_data()$x,plot_data()$y,main=input$title,type="l")
  })
  
  
  
  output$gen_by <- renderText({
    glue("Chart genereted by: {input$generated_by}")
  })
  
  
  
  output$plot_table <- renderTable({
    validate(need(!is.null(plot_data()),message = "novaliddata"))
    plot_data()
  })
  
  
  
  observeEvent(input$new,{
    print("buttonClicked")
    print(input$name)
  })
  
}


shinyApp(ui, server)

